// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebfbynaopkeezutglbgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViZmJ5bmFvcGtlZXp1dGdsYmdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODc0MjUsImV4cCI6MjA2NTU2MzQyNX0.OIAw8t3NtBraFgZ_Ocz7pTCasR1PuIlGkZJ5VxhQdIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);